apiVersion: v1
kind: ServiceAccount
metadata:
  name: osf-gateway
  namespace: osf

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: osf-pod-manager
  namespace: osf
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: osf-gateway-pod-manager
  namespace: osf
subjects:
- kind: ServiceAccount
  name: osf-gateway
  namespace: osf
roleRef:
  kind: Role
  name: osf-pod-manager
  apiGroup: rbac.authorization.k8s.io
